### ISSUE TITLE
Cannot equip backpacks

### ISSUE THREAD

**Issue by ToxicShourin** [fzzyhmstrs/piu#10]
Not sure why this is a thing but you cannot equip a backpack unlike the armored pack. This is kinda dumb if you include the super expensive crafting required to make just 1 complete backpack that can only function while staying in the inventory making this 1 extremely expensive shulker box with the only advantage being that you can access by pressing the B key and not having to place on the ground.

**Comment by fzzyhmstrs** [comment]
This is not an actual issue, but thank you for the opinion
