### ISSUE TITLE
cannot attach back pack bag to frame please fix.

### ISSUE THREAD

**Issue by ToxicShourin** [fzzyhmstrs/piu#11]
Cannot attach backpack bag to frame in pack bench.
![2023-02-21_17 16 37](https://user-images.githubusercontent.com/55967924/220471149-af3e3695-383b-45d2-a215-d46bc214d894.png)

**Comment by fzzyhmstrs** [comment]
you can't attach a large pack directly to the frame. You need to upgrade a small pack into the large one.

https://github.com/fzzyhmstrs/piu/wiki/Backpacks
