### ISSUE TITLE
[Incompability] Lunchpack is not compatible with any of modded foods

### ISSUE THREAD

**Issue by ghost** [fzzyhmstrs/piu#14]
I've tried it with Crafty Cuisine and Grillin Galore and no foods from there can be putted in backpack. If included compability is not an option, I want to suggest creating a config to ad IDs of food that can be putted in lunchpack

**Comment by fzzyhmstrs** [comment]
There is a tag that can be used to add custom foods: [https://github.com/fzzyhmstrs/piu/wiki/Item-Tags](https://github.com/fzzyhmstrs/piu/wiki/Item-Tags). You can also use the `c:foods` tag
