### ISSUE TITLE
Cannot Open Backpacks after renaming

### ISSUE THREAD

**Issue by Mace-The-Ace** [fzzyhmstrs/piu#5]
Hello! The issue I had was I was renaming my backpack to match the contents that were going into the backpack but once I did that, that backpack will no longer open and I cannot get access to my items.

**Comment by fzzyhmstrs** [comment]
I was able to replicate this and have a fix out with version 0.2.2. Fortunately the issue isn't deleting the inventory, so you should be able to open your pack with items still in it after updating.
![image](https://user-images.githubusercontent.com/72876796/209820705-9d32ba67-87ce-4db3-91a1-a0bbfd395c4f.png)
