### ISSUE TITLE
Shift clicking large stacks into inventory deletes upon reentering the game.

### ISSUE THREAD

**Issue by Boodlyneck** [fzzyhmstrs/piu#6]
Hello! =D

fabric-loader-0.14.12-1.19.2
pack_it_up-0.2.4+1.19.jar

If I shift-click stacks of 256 out of backpacks it puts the entire stack in my inventory which then gets deleted when I leave and reenter a game.

I expected it to split the stack into smaller allowable-sized stacks when I shift-clicked it.

Cool mod btw, I hope you get it all worked out.

(sorry for the low-quality video, but only allowed 10 Mb file size =D)

https://user-images.githubusercontent.com/68196907/210903216-c62655da-ce73-4421-81ae-2c837f4b36dc.mp4

**Comment by fzzyhmstrs** [comment]
Thanks for the report! Looking into it right now

**Comment by fzzyhmstrs** [comment]
Fixed in version 0.2.5

**Comment by Boodlyneck** [comment]
Wow! Fast work!
