### ISSUE TITLE
Lunchpack Bag won't connect with frame in pack bench.

### ISSUE THREAD

**Issue by McKitten** [fzzyhmstrs/piu#9]
Version: 0.3.0+1.19
Pack: DarkRPG 5.2.8
I have 2 packs, the first was a Large Backpack bag which i placed in the pack bench with the non-large/base version on its frame. This output a large + frame with a separate base version as planned.
I then upgraded the base version to a lunchpack bag and created a new frame, however the two refuse to create the usable version.

**Comment by fzzyhmstrs** [comment]
The lunchpack also upgrades from a basic pack, not from an empty frame. All roads start with basic pack. I have considered making the low tier bags craft directly with the frame, but it's not currently implemented that way.

**Comment by McKitten** [comment]
I feel the description should be altered then. It says to attach to a frame rather than a backpack. 

Also is there a way for modpack authors to add support for food mods like farmers delight or croptopia? Or maybe some exceptions to those two like Gobber Gooey _x_ or ecologic's/quarks coconut/crab. Not sure if the creators were just lazy or if it is on your wish list still :)

**Comment by fzzyhmstrs** [comment]
Yes you can add unsupported modded food items (or other tiems to other packs). There are a set of special tags that can be used, and various `c:` tags also work. For the lunchpack I believe that is `c:foods`

Special tags:

[https://github.com/fzzyhmstrs/piu/wiki/Item-Tags](https://github.com/fzzyhmstrs/piu/wiki/Item-Tags)
